### ISSUE TITLE
Cannot select 16 chunks for hap encoding

### ISSUE THREAD

**Issue by reno-** [Vidvox/hap-in-avfoundation#20]
8 is the maximum on different macpro. With other software (smode), i can choose 16.

**Comment by mrRay** [comment]
i increased the max number of chunks to 16- but i also added an alert if the number of chunks exceeds 8, because i still think that's a sane maximum for most purposes.  generally speaking, performance starts getting noticeably worse if the number of chunks exceeds the number of logical cores...

commit b54619d87d6d5c5a1da57a624489c44baf83ac64/release 1.6.9.1 contain these changes.  if you need to encode movies with > 16 chunks, you can simply change AVAssetWriterInput.h, ln 20:

```
#define				HAPQMAXCHUNKS 16
```


cheers
: : ray

**Comment by reno-** [comment]
Thank you @mrRay !!
